# 1、tensor

#tensor的操作和numpy操作类似，有两种形式
1. torch.function(a,b)
2. a.function(b)

其中的a和b均为tensor

## 1.广播

In [1]:
import torch as t
import torch.nn as nn
from torch.autograd import Variable

In [2]:
#可以从外面的方括号知道这个数据是多少维度的
a = t.ones(3,2)
b = t.zeros(2, 3, 1)
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])


In [3]:
a + b

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

## 2.squeeze 
**squeeze是一个去掉维度的操作，其中unsqueeze是增加维度的操作，传入的参数是维度的序号，从0开始**
[参考链接](https://blog.csdn.net/flysky_jay/article/details/81607289)

In [4]:
a.unsqueeze(0).expand(2,3, 2) + b.expand(2, 3, 2)
a + b

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

## 3.numpy和tensor之间的转换

In [5]:
import numpy as np

In [6]:
#定义一个numpy单位矩阵
a = np.ones([2,3], dtype = np.float32)
a

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

**将numpy转成tensor的两种方法**

In [7]:
#将numpy转成tensor
b = t.from_numpy(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
c = t.Tensor(a)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

三者共享内存

In [10]:
a[1,1] = 10
print(a)
print(b)
print(c)

[[ 1.  1.  1.]
 [ 1. 10.  1.]]
tensor([[ 1.,  1.,  1.],
        [ 1., 10.,  1.]])
tensor([[ 1.,  1.,  1.],
        [ 1., 10.,  1.]])


## 4.tensor内存的存储

一个tensor由两个部分组成:头部和数据存储区域
其中头部相当于一个指针，表示着这个数据代表的类型以及数据相关的指标

1)头部信息不同却可能有着相同的storage()

In [11]:
a = t.arange(0,6)
a

tensor([0, 1, 2, 3, 4, 5])

In [12]:
a.storage()

 0
 1
 2
 3
 4
 5
[torch.LongStorage of size 6]

In [13]:
b = a.view(2,3)
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [14]:
b.storage()

 0
 1
 2
 3
 4
 5
[torch.LongStorage of size 6]